package code.model.objects;

import code.utils.HelperFunctions;

public class PlanetObject {
    /**
     * Gravitational Constant
     */
    public static double G = 6.6743e-20;
    private final double[] COORDINATES = new double[3];
    private final double[] VELOCITY = new double[3];
    private double mass;
    private double radius;

    /**
     * NASA object code (for testing)
     */
    private int planetCode;
    //Position for end position of planet(only used for tests)
    private double[] targetPosition;
    private double[] acceleration;


    public PlanetObject(double[] coordinates, double[] velocity) {
        setCoordinates(coordinates);
        setVelocity(velocity);
    }

    /**
     * Constructor for NASA data (for testing)
     *
     * @param planetCode an int representing the NASA planet code corresponding to the celestial body
     *                   which the instance of this class represents
     */
    public PlanetObject(int planetCode) {
        this.planetCode = planetCode;
    }


    /**
     * This function can calculate how much force does planet 2 apply to planet 1 and turn it to acceleration.
     * It uses Newton’s law of universal gravity for 3 dimensions.
     *
     * @param planetObject the planet that is interacting with the current planet
     * @return the acceleration vector of the force generated by the attraction between planet 1 and planet 2
     */
    public double[] accelerationBetween(PlanetObject planetObject) {
        double[] force = new double[3];
        double[] positionalVector;
        double[] acceleration = new double[3];

        positionalVector = HelperFunctions.subtract(COORDINATES, planetObject.getCoordinates());

        double distance = 1 / HelperFunctions.getDistanceBetweenWithVectors(COORDINATES, planetObject.getCoordinates());
        if (distance == Double.POSITIVE_INFINITY)
            throw new IllegalArgumentException("The two celestial bodies are at the same location");

        for (int i = 0; i <= 2; i++) {
            force[i] = -G * mass * planetObject.getMass() * distance * distance * distance * positionalVector[i];
            acceleration[i] = force[i] / mass;
        }
        return acceleration;
    }


//  GETTER and SETTERS

    /**
     * Retrieves the coordinates of the modeled object as an array of doubles.
     *
     * @return an array of doubles representing the coordinates of the modeled object.
     */
    public double[] getCoordinates() {
        return COORDINATES;
    }

    /**
     * Sets the coordinates of the modeled object.
     *
     * @param coordinates an array of doubles representing the new coordinates for the modeled object.
     */
    public void setCoordinates(double[] coordinates) {
        COORDINATES[0] = coordinates[0];
        COORDINATES[1] = coordinates[1];
        COORDINATES[2] = coordinates[2];
    }

    /**
     * Retrieves the velocity of the modeled object.
     *
     * @return an array of doubles representing the velocity of the modeled object.
     */
    public double[] getVelocity() {
        return VELOCITY;
    }

    /**
     * Sets the velocity of the modeled object.
     *
     * @param velocity an array of doubles containing the new velocity for the modeled object.
     */
    public void setVelocity(double[] velocity) {
        VELOCITY[0] = velocity[0];
        VELOCITY[1] = velocity[1];
        VELOCITY[2] = velocity[2];
    }

    public void setMass(double mass) {
        this.mass = mass;
    }

    /**
     * Retrieves the mass of the modeled object.
     *
     * @return a long representing the mass of the modeled object.
     */
    public double getMass() {
        return mass;
    }

    public double[] getAcceleration() {
        return acceleration;
    }

    public void setAcceleration(double[] acceleration) {
        this.acceleration = acceleration;
    }

    public double getRadius() {
        return radius;
    }

    public void setRadius(double radius) {
        this.radius = radius;
    }

    public int getPlanetCode() {
        return planetCode;
    }

    public double[] getTargetPosition() {
        return targetPosition;
    }

    public void setTargetPosition(double[] targetPosition) {
        this.targetPosition = targetPosition;
    }
}
